module.exports = {
  apps: [
    {
      name: 'nextapp-backend',
      cwd: '/var/www/nextapp/backend',
      script: 'node',
      args: 'dist/server.js',
      interpreter: 'none',
      env_file: '/var/www/nextapp/backend/.env',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        CORS_ORIGIN: 'http://155.94.150.168,http://155.94.150.168:83,http://localhost:83,http://localhost:5000',
        DB_HOST: 'localhost',
        DB_PORT: '5432',
        DB_USER: 'koncepts_user',
        DB_PASSWORD: 'Postgress',
        DB_NAME: 'koncepts_dev',
        DB_SSL: 'false',
        DATABASE_URL: 'postgresql://koncepts_user:Postgress@localhost:5432/koncepts_dev',
        JWT_SECRET: 'dev_secret_key_12345',
        JWT_EXPIRY: '24h',
        LOG_LEVEL: 'debug',
        LOG_FORMAT: 'simple',
      },
      error_file: '/var/www/nextapp/logs/backend-error.log',
      out_file: '/var/www/nextapp/logs/backend-out.log',
      log_file: '/var/www/nextapp/logs/backend-combined.log',
      time: true,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'nextapp-frontend',
      cwd: '/var/www/nextapp',
      script: 'npx',
      args: 'vite --host 0.0.0.0 --port 83',
      interpreter: 'none',
      env: {
        NODE_ENV: 'development',
        PORT: 83,
      },
      error_file: '/var/www/nextapp/logs/frontend-error.log',
      out_file: '/var/www/nextapp/logs/frontend-out.log',
      log_file: '/var/www/nextapp/logs/frontend-combined.log',
      time: true,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
  ],
};
