-- Align SalesQuotation with sales invoice financial / customer fields
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "customerType" TEXT NOT NULL DEFAULT 'registered';
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "customerId" TEXT;
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "overallDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "freightCharges" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "tax" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "taxPercentage" DOUBLE PRECISION;
