ALTER TABLE "PurchaseImportRequestItem"
ADD COLUMN "khiQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "isbQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "otherQuantity" INTEGER NOT NULL DEFAULT 0;
