ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "workingDays" INTEGER NOT NULL DEFAULT 26;
ALTER TABLE "EmployeeTransaction" ADD COLUMN IF NOT EXISTS "absentDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
