-- AlterTable
ALTER TABLE "PurchaseOrder" ADD COLUMN "currency" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN "conversionRate" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "PurchaseOrder" ADD COLUMN "fcTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PurchaseOrderItem" ADD COLUMN "fcRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN "fcAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN "weight" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN "totalWeight" DOUBLE PRECISION NOT NULL DEFAULT 0;
